#pragma once

enum XACT_WAVEBANK_SOUNDS
{
    XACT_WAVEBANK_SOUNDS_WIND = 0,
    XACT_WAVEBANK_SOUNDS_EXAMPLE2 = 1,
    XACT_WAVEBANK_SOUNDS_MENUCLICK = 2,
    XACT_WAVEBANK_SOUNDS_WRONGMENUCLICK = 3,
    XACT_WAVEBANK_SOUNDS_LANTERNON = 4,
    XACT_WAVEBANK_SOUNDS_LANTERNOFF = 5,
    XACT_WAVEBANK_SOUNDS_LANTERNON2 = 6,
};

#define XACT_WAVEBANK_SOUNDS_ENTRY_COUNT 7
