#pragma once

enum XACT_WAVEBANK_SOUNDS
{
    XACT_WAVEBANK_SOUNDS_BACKGROUND = 0,
    XACT_WAVEBANK_SOUNDS_LANTERNON = 1,
    XACT_WAVEBANK_SOUNDS_LANTERNOFF = 2,
    XACT_WAVEBANK_SOUNDS_MENUCLICK = 3,
    XACT_WAVEBANK_SOUNDS_MENUSELECTIONCLICK = 4,
};

#define XACT_WAVEBANK_SOUNDS_ENTRY_COUNT 5
