#pragma once

enum XACT_WAVEBANK_SOUNDS
{
    XACT_WAVEBANK_SOUNDS_BACKGROUND = 0,
    XACT_WAVEBANK_SOUNDS_LANTERNON = 1,
    XACT_WAVEBANK_SOUNDS_LANTERNOFF = 2,
    XACT_WAVEBANK_SOUNDS_MENUSELECTIONCLICK = 3,
    XACT_WAVEBANK_SOUNDS_ATTACKSOUND = 4,
    XACT_WAVEBANK_SOUNDS_CASTLEMUSIC = 5,
    XACT_WAVEBANK_SOUNDS_CAVEMUSIC = 6,
    XACT_WAVEBANK_SOUNDS_DEATHSOUND = 7,
    XACT_WAVEBANK_SOUNDS_FALLINGSOUND = 8,
    XACT_WAVEBANK_SOUNDS_FINDTHEEMBER = 9,
    XACT_WAVEBANK_SOUNDS_INTROTOFLAMEBEARER = 10,
    XACT_WAVEBANK_SOUNDS_JUMPSOUND = 11,
    XACT_WAVEBANK_SOUNDS_MINIBOSSATTACKSOUND = 12,
    XACT_WAVEBANK_SOUNDS_SNOWMUSIC = 13,
    XACT_WAVEBANK_SOUNDS_TAKINGDAMAGEMINIBOSSSOUND = 14,
    XACT_WAVEBANK_SOUNDS_TAKINGDAMAGESOUND = 15,
    XACT_WAVEBANK_SOUNDS_WIND = 16,
    XACT_WAVEBANK_SOUNDS_WRONGMENUCLICK = 17,
};

#define XACT_WAVEBANK_SOUNDS_ENTRY_COUNT 18
